server:
  port: 8020
spring:
  application:
    name: menu
  datasource:
    url: jdbc:mysql://localhost:3306/outsidecatering?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: wangqing
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.chase.entity